# Generated by Django 4.0.3 on 2022-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medium', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
